live_config_reload = true

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

[cursor]
unfocused_hollow = true

[debug]
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Propo"
style = "Light Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Propo"
style = "Medium"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Paste"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Copy"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "L"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Space"
mode = "Vi|~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Y"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "E"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "G"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "G"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "U"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "D"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Copy"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "V"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "V"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "V"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "V"
mode = "Vi|~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "J"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "H"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "L"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Up"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Down"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Left"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Right"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Key0"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Key4"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Key6"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "H"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "M"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "L"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "W"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "E"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "W"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "E"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Key5"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Slash"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Slash"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "N"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "N"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mode = "Search|Vi"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Escape"
mode = "Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "U"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "W"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "P"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "N"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Up"
mode = "Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Down"
mode = "Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mode = "Search|~Vi"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mode = "Search|~Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[mouse.bindings]]
action = "ReceiveChar"
mouse = "Right"

[[mouse.bindings]]
action = "ReceiveChar"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "ReceiveChar"
mode = "~Vi"
mouse = "Middle"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"
dynamic_title = false

[window.padding]
x = 0

[shell]
program = "/bin/zsh"
